version: '3.9'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs
    restart: always
    volumes:
      - '.:/app/:rw'
    ports:
      - '80:80'
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - app
  mongodb:
    build:
      context: ./docker/mongodb
      dockerfile: Dockerfile
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    networks:
      - app

networks:
  app:
